#!/bin/sh

SRCPATH=src
BINPATH=bin

LOGOFILE=EarDrumLogo_v1.jpg
IMGREPO=http://www.fabianos.de/eardrummer/img

echo "INFO: You will need javaJRE OR openJDK installed for compiling."

if [ -e $BINPATH ]
then echo "Folder '$BINPATH' exists."
else echo "making folder '$BINPATH'"; mkdir $BINPATH
fi
echo -n "Compiling EARDrum project.. "
javac -g -sourcepath $SRCPATH -d $BINPATH $SRCPATH/init/Init.java
echo "done."

cd img
./create_images.sh
# get logo
if [ -e $LOGOFILE ]
then echo "Logofile $LOGOFILE exists."
else wget "$IMGREPO/$LOGOFILE"
fi
cd ..

if [ -e $BINPATH ]
then echo "Execute './run' now to start EARDrum program."
fi
